# Assignment-2 Numpy function

In [1]:
import jovian

In [2]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "181b226/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"


[jovian] Committed successfully! https://jovian.ml/181b226/numpy-array-operations


'https://jovian.ml/181b226/numpy-array-operations'

In [3]:
import numpy as np

# Function 1 - numpy.char.add
This function concatenates element-wise the strings of two matrices.

In [4]:
# Example 1 - working 
arr1 = [["apple", "manago"],
        ["banana", "watermelon"]]
arr2 = [["dog", "lion"],
        ["cat", "tiger"]]
np.char.add(arr1, arr2)

array([['appledog', 'managolion'],
       ['bananacat', 'watermelontiger']], dtype='<U15')

In [5]:
# Example 2 - working
arr1 = [["apple", "manago"],
        ["banana", "watermelon"]]
arr2 = [["dog", "lion"],
        ["cat", "tiger"]]
arr1 = np.char.add(arr1, " ")
np.char.add(arr1, arr2)

array([['apple dog', 'manago lion'],
       ['banana cat', 'watermelon tiger']], dtype='<U16')

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [["L", "I"],
        ["D", "S"]]
arr2 = [[1, 2],
        [3, 4]]
np.char.add(arr1, arr2)

TypeError: can only concatenate str (not "numpy.int32") to str

One way to fix this is to enter the numbers as charachters (strings of length 1).

this is about char add function.

In [7]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "181b226/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"


[jovian] Committed successfully! https://jovian.ml/181b226/numpy-array-operations


'https://jovian.ml/181b226/numpy-array-operations'

# Function 2 - Transpose
This function permutes the dimension of the given array. It returns a view wherever possible. The function takes the following parameters: numpy.transpose(arr, axes), Here arr:The array to be transposed, axes:List of ints, corresponding to the dimensions. By default, the dimensions are reversed

In [8]:
# Example 1 - working
a = np.arange(16).reshape(2,2,4) 

print ('The original array is:' )
print (a)  
print ('\n') 

print('The transposed array is:') 
print (np.transpose(a,(1,0,2)))

The original array is:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


The transposed array is:
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [9]:
# Example 2 - working
a = np.arange(12).reshape(3,4) 

print ('The original array is:' )
print (a)  
print ('\n') 

print('The transposed array is:') 
print ( np.transpose(a))

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [10]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.arange(12).reshape(3,4) 

print ('The original array is:' )
print (a)  
print ('\n') 

print('The transposed array is:') 
print ( np.transpose(a,0))

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:


ValueError: axes don't match array

Explanation about example (why it breaks and how to fix it): Here the program did not execute beacause the axis mentioned are not correct depending on the rows and coloums present we need to adjust the axis. In the above program the axis should be of 2D form.

This function is used to get transform of a array. And also can be used for changes the axis of elements.

In [11]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "181b226/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"


[jovian] Committed successfully! https://jovian.ml/181b226/numpy-array-operations


'https://jovian.ml/181b226/numpy-array-operations'

# Function 3 - Swapaxes
This function interchanges the two axes of an array. A view of the swapped array is returned. The function takes the following parameters:numpy.swapaxes(arr, axis1, axis2), Here arr:Input array whose axes are to be swapped,axis1:An int corresponding to the first axis,axis2:An int corresponding to the second axis.

In [12]:
# Example 1 - working
a = np.arange(8).reshape(2,2,2) 

print ('The original array:') 
print (a) 
print ('\n')  
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 

print ('The array after applying the swapaxes function:' )
print (np.swapaxes(a, 2, 0))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


The array after applying the swapaxes function:
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [13]:
# Example 2 - working
a = np.arange(8).reshape(2,2,2) 

print ('The original array:') 
print (a) 
print ('\n')  
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 

print ('The array after applying the swapaxes function:' )
print (np.swapaxes(a, 1, 2))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


The array after applying the swapaxes function:
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [14]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.arange(8).reshape(2,2,2) 

print ('The original array:') 
print (a) 
print ('\n')  
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 

print ('The array after applying the swapaxes function:' )
print (np.swapaxes(a, 1, 3))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


The array after applying the swapaxes function:


AxisError: axis2: axis 3 is out of bounds for array of dimension 3

Explanation about example (why it breaks and how to fix it): Here error is because the specifed axis is out of bound. To correct this we can check the boundary of the array and take care of the value when we specify the axis.

This function is used to swap values when required.

# Function 4 - Horizontal split
The numpy.hsplit is a special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array.

In [15]:
# Example 1 - working
a = np.arange(16).reshape(4,4) 

print ('First array:' )
print (a) 
print ('\n')  

print( 'Horizontal splitting:') 
b = np.hsplit(a,2) 
print(b )

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [17]:
# Example 2 - working
a = np.arange(12).reshape(4,3) 

print ('First array:' )
print (a) 
print ('\n')  

print( 'Horizontal splitting:') 
b = np.hsplit(a,3) 
print(b )

First array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Horizontal splitting:
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [18]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.arange(12).reshape(4,3) 

print ('First array:' )
print (a) 
print ('\n')  

print( 'Horizontal splitting:') 
b = np.hsplit(a,5) 
print(b )


First array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Horizontal splitting:


ValueError: array split does not result in an equal division

Explanation about example (why it breaks and how to fix it): Here the error os because 5 is not a factor of 12 so, dividing the array equally is not possible. So, to fix this we need to take a number which is factor of the size of array.

This function is used to divide the array into equal parts horizontally by a given factor of elements for set.



In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "181b226/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"


[jovian] Committed successfully! https://jovian.ml/181b226/numpy-array-operations


'https://jovian.ml/181b226/numpy-array-operations'

# Function 5 - Append
This function adds values at the end of an input array. The append operation is not inplace, a new array is allocated. Also the dimensions of the input arrays must match otherwise ValueError will be generated.

The function takes the following parameters:numpy.append(arr, values, axis). Here,arr:Input array,values:To be appended to arr. It must be of the same shape as of arr (excluding axis of appending),axis:The axis along which append operation is to be done. If not given, both parameters are flattene

In [20]:
# Example 1 - working
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:' )
print (a)
print ('\n')  

print ('Append elements to array:' )
print (np.append(a, [7,8,9])) 

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


In [21]:
# Example 2 - working
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:' )
print (a)
print ('\n') 
print ('Append elements along axis 0:' )
print( np.append(a, [[7,8,9]],axis = 0) )

First array:
[[1 2 3]
 [4 5 6]]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:' )
print (a)
print ('\n') 
print ('Append elements along axis 0:' )
print( np.append(a, [[5,5,5,5]],axis = 0) )

First array:
[[1 2 3]
 [4 5 6]]


Append elements along axis 0:


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

Explanation about example (why it breaks and how to fix it): Size of the provided new array is out of range so it is difficult to concatenate. To fix this we need to make sure the size of the given array is equal to the original array.

This function can be used to add elements in array when required. 

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "181b226/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"


[jovian] Committed successfully! https://jovian.ml/181b226/numpy-array-operations


'https://jovian.ml/181b226/numpy-array-operations'

# THANK YOU